name = "wedding-api"
main = "worker.js"
compatibility_date = "2024-09-01"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "wedding-db"
database_id = "2e4756fb-7385-4bb9-b629-918de093542b"
